[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[31m[1mERROR   [0m root:test_ryvue.py:70 userManagement_048断言失败，用例数据为：{'userName': 'userManagement_048', 'nickName': 'userManagement_048', 'password': '123456', 'status': '0', 'postIds': [], 'roleIds': [], 'phonenumber': '17502502921'}期望数据为：{'msg': '操作成功', 'code': 200}服务器返回的期望数据：{"msg":"新增用户'userManagement_048'失败，手机号码已存在","code":500}
[31m[1mERROR   [0m root:__init__.py:33 断言失败