[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[31m[1mERROR   [0m root:test_ryvue.py:70 userManagement_079断言失败，用例数据为：{'userName': 'userManagement_079', 'nickName': 'userManagement_079', 'password': '123456', 'status': '0', 'postIds': [], 'roleIds': [], 'sex': '-1'}期望数据为：{'msg': '操作失败', 'code': 500}服务器返回的期望数据：{"msg":"\n### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'sex' at row 1\n### The error may exist in URL [jar:file:/ruoyi/app/ruoyi-admin.jar!/BOOT-INF/lib/ruoyi-system-3.8.7.jar!/mapper/system/SysUserMapper.xml]\n### The error may involve com.ruoyi.system.mapper.SysUserMapper.insertUser-Inline\n### The error occurred while setting parameters\n### SQL: insert into sys_user(                  user_name,       nick_name,                         sex,       password,       status,       create_by,            create_time    )values(                  ?,       ?,                         ?,       ?,       ?,       ?,            sysdate()    )\n### Cause: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'sex' at row 1\n; Data truncation: Data too long for column 'sex' at row 1; nested exception is com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'sex' at row 1","code":500}
[31m[1mERROR   [0m root:__init__.py:33 断言失败