[32mINFO    [0m root:__init__.py:27 功能的名称为：test_ryvue 功能的描述为：None
[31m[1mERROR   [0m root:test_ryvue.py:70 userManagement_041断言失败，用例数据为：{'userName': 'userManagement_041', 'nickName': 'userManagement_041', 'password': '12341234123412341', 'status': '0', 'postIds': [], 'roleIds': []}期望数据为：{'msg': '操作失败', 'code': 500}服务器返回的期望数据：{"msg":"操作成功","code":200}
[31m[1mERROR   [0m root:__init__.py:33 断言失败